### ISSUE TITLE
[CORS problem]

### ISSUE THREAD

**Issue by rvvergara** [efrapp/library#3]
I am not sure if in any of the third party modules we included in the project does some fetching, but whenever I open `index.html` in my browser I get this:

![image](https://user-images.githubusercontent.com/6015315/62666047-54d4e100-b9b4-11e9-8f8c-3200810149fd.png)

**Comment by efrapp** [comment]
Hi @rvvergara,
Ok to solve this you need to run the project through an Http server, please follow these steps:
1. install the server using: `npm install http-server -g`
2. Run the server in the console with `http-server` and check the url the server will listen to
3. In the browser go to the url provided by `http-server`, normally it is `http://127.0.0.1:8080/`

I'm going to update the documentation to state this.
